[package]
name = "rust-samples"
version = "0.1.0"
authors = ["prasad iyer <p.c.iyer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
